name: opennms-kafka-collectionset-consumer
run-name: Build kafka-collectionset-consumer
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Prepare env
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk maven
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build it
        run: |
          mvn -DskipTests=true clean install
      - name: Persist build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opennms-collectionset-kafka-consumer.jar
          path: ./target/opennms-collectionset-kafka-consumer.jar
      - name: Release ${{ github.ref_name }}
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            ./target/opennms-collectionset-kafka-consumer.jar
